.pragma library
// Generated by yeetkit-omarchy build. Edit yeetkit.config.js, not this.

var id = "cx.yeet.yeet-ai";
var name = "yeet-ai";
var yeetArgs = ["run","-y","-q"];
var barImage = "assets/fecm.png";

/* The command `script -c` runs: yeet with the app, quoted for sh. */
function shellCommand(appPath) {
  return ["yeet"].concat(yeetArgs).concat([appPath]).map(quote).join(" ");
}

function quote(word) {
  return "'" + String(word).replace(/'/g, "'\\''") + "'";
}
