.pragma library
// Generated by yeetkit-omarchy build. Edit yeetkit.config.js, not this.

var id = "cx.yeet.askai";
var name = "askai";
var yeetArgs = ["run","-y","-q"];

/* The command `script -c` runs: yeet with the app, quoted for sh. */
function shellCommand(appPath) {
  return ["yeet"].concat(yeetArgs).concat([appPath]).map(quote).join(" ");
}

function quote(word) {
  return "'" + String(word).replace(/'/g, "'\\''") + "'";
}
